version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - "NODE_ENV=prod"
      - "PG_URL=postgres://postgres:pass123@db:5432/perdiem"
  db:
    image: "postgres:11.5"
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=pass123"
      - "POSTGRES_DB=perdiem"


